#!/bin/bash

docker run --rm -it \
  -v $PWD:/tmp/working \
  -w=/tmp/working \
  -p 8888:8888  \
  kaggle/python \
  jupyter notebook --no-browser --allow-root --ip="0.0.0.0" --notebook-dir=/tmp/working

