#!/bin/bash

DOCKER_FLAGS=
if [[ "$GPU" = 1 ]]; then
  DOCKER_FLAGS='--runtime=nvidia'
fi

docker run ${DOCKER_FLAGS} --rm -it \
  -v $PWD:/tmp/working \
  -w=/tmp/working \
  -p 8888:8888  \
  agatan/python-science \
  jupyter notebook --no-browser --allow-root --ip="0.0.0.0" --notebook-dir=/tmp/working

